/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { BlogView } from "./BlogView";
import { BlogViewCountArgs } from "./BlogViewCountArgs";
import { BlogViewFindManyArgs } from "./BlogViewFindManyArgs";
import { BlogViewFindUniqueArgs } from "./BlogViewFindUniqueArgs";
import { DeleteBlogViewArgs } from "./DeleteBlogViewArgs";
import { BlogViewService } from "../blogView.service";
@graphql.Resolver(() => BlogView)
export class BlogViewResolverBase {
  constructor(protected readonly service: BlogViewService) {}

  async _blogViewsMeta(
    @graphql.Args() args: BlogViewCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [BlogView])
  async blogViews(
    @graphql.Args() args: BlogViewFindManyArgs
  ): Promise<BlogView[]> {
    return this.service.blogViews(args);
  }

  @graphql.Query(() => BlogView, { nullable: true })
  async blogView(
    @graphql.Args() args: BlogViewFindUniqueArgs
  ): Promise<BlogView | null> {
    const result = await this.service.blogView(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => BlogView)
  async deleteBlogView(
    @graphql.Args() args: DeleteBlogViewArgs
  ): Promise<BlogView | null> {
    try {
      return await this.service.deleteBlogView(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
